# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
# permalink: /:title
# https://help.github.com/articles/migrating-your-pages-site-from-maruku
markdown: kramdown

highlighter: pygments
paginate: 20 # pagination based on number of posts
paginate_path: "page/:num"

# These paths are to the main pages Jekyll-Bootstrap ships with.
# Some JB helpers refer to these paths; change them here if needed.
#
categories_path : categories.html
tags_path : tags.html

BASE_PATH : http://loshine.github.io
# BASE_PATH : http://localhost:4000

title : 饭饭的小窝



author:
  name: talk2ankan
  role: Loshine
  email: loshine1992@gmail.com
  github: Loshine
  #twitter: talk2ankan
  #facebook: talk2ankan
  #googleplus: +AnkanBiswasWorkspace
  bio: "PHP是最好的编程语言！233"
  #uno-dbyll: https://raw.githubusercontent.com/talk2ankan/uno-dbyll/gh-pages/uno-dbyll.png
  uno-dbyll: http://7xl94a.com1.z0.glb.clouddn.com/20140122112618_ZXznW.thumb.700_0.jpeg


gems:
  - jekyll-sitemap